fix: update UiRecipe blueprint
equinor/data-modelling-storage-service pull request #333
Opened 2023-01-10 07:34 UTC by KristianKjerstad

## What does this pull request change?
various bug fixes
## Why is this pull request needed?
various bug fixes
## Issues related to this change:

2023-01-10 07:35 UTC, KristianKjerstad commented
bug with object type

![image](https://user-images.githubusercontent.com/69512295/211489761-f9db2ba9-fb8e-4200-9fff-c51018e38f1b.png)

2023-01-10 14:17 UTC, soofstad requested changes
This has been discussed before.
"name" should not have a special treatment in "CreateEntity".
If there is a bug now, it should be fixed in some other way

2023-01-11 08:53 UTC, KristianKjerstad commented
> This has been discussed before. "name" should not have a special treatment in "CreateEntity". If there is a bug now, it should be fixed in some other way

fixed here instead https://github.com/equinor/dm-core-packages/pull/44/files

2023-01-11 09:32 UTC, soofstad approved these changes

2023-01-11 09:51 UTC, merged