Test/move blueprints into test 2
equinor/data-modelling-storage-service pull request #585
Opened 2023-09-25 10:03 UTC by pbullhove

## What does this pull request change?

## Why is this pull request needed?

## Issues related to this change:

2023-09-26 06:58 UTC, collinlokken requested changes
Nice to finally get a bit more understandable tests and names 🤩 I would remove the "...", and maybe add value to the `name` attribute where name is an empty string. Finally it would be nice to rename the `containement_example` folder to something more generic.

2023-09-26 06:58 UTC, collinlokken commented on src/tests/unit/services/document_service/test_remove.py
> +                "name": "",
Maybe have a name for clarity?

2023-09-26 06:58 UTC, collinlokken commented on src/tests/unit/services/document_service/test_remove.py
> +                "...": {
to me this shows as "...", is this intended?

2023-09-28 08:12 UTC, collinlokken requested changes

2023-09-28 10:47 UTC, pbullhove commented on src/tests/unit/common/utils/validators/test_validate_entity.py
> +            recipe_provider=MockStorageRecipeProvider(
done

2023-09-28 10:47 UTC, pbullhove commented on src/tests/unit/services/document_service/test_remove.py
> +                    "not_in_blueprint": {
done

2023-09-29 08:55 UTC, collinlokken approved these changes
Very nice!

2023-09-29 08:59 UTC, merged